### ISSUE TITLE
rocHPCG cause amdgpu driver crash

### ISSUE THREAD

**Issue by EllisLambda** [ROCm/rocHPCG#66]
The amdgpu driver crashes when the parameters size of rocHPCG exceeds 32 16 16 on the Ryzen 7840HS (gfx1103_r1, LLVM 16.0.6, DRM 3.49, 6.2.12-1-default) rocm 5.6
dmesg crash log: https://paste.opensuse.org/pastes/fbaa717e5a1a
If the size of the parameters not exceed the specified limits, the rocHPCG works normally.
![图片](https://github.com/ROCmSoftwarePlatform/rocHPCG/assets/18545102/5f197183-65cb-41aa-b944-cdceb1fee5b0)

**Comment by ntrost57** [comment]
Currently, we do not support RDNA in rocHPCG.
